### ISSUE TITLE
[Feature request] Notification to Telegram

### ISSUE THREAD

**Issue by Keonik1** [jansppenrade2/Docker-Container-Updater#2]
Hello again.

I would like to suggest one more feature - notifications in telegram.
To get access to mail often requires a number of efforts, which is not always convenient, but to look at the notification in Telegram is very quick and easy.

I understand that I will have to almost duplicate the `Send-MailNotification()` function, so I will just write the nuances.

0. The formatting can be implemented via HTML, so maybe you don't even have to rewrite anything, but use the message composing code for the mail notification.
1. The maximum size of one message is 4096 characters (for users with and without premium subscription) and you can't send more than this limit at a time, so you may have to write a message splitter.
```json
{
  "ok": false,
  "error_code": 400,
  }, "description": "Bad Request: message is too long"
}
```
2. Formatting is **not** factored into the character count of the message, i.e. you can send a 4200 character message with formatting taken into account.
3. Formatting guideline: https://core.telegram.org/bots/update56kabdkb12ibuisabdubodbasbdaosd
4. Example command to send:
```bash
API_TOKEN="<your_api_token>"
CHAT_ID="<your_chat_id>"

# Set the message text
MESSAGE_MD="*bold \*text*
_italic \*text_
__underline__
~strikethrough~
||spoiler||
*bold _italic bold ~italic bold strikethrough ||italic bold strikethrough spoiler||~ __underline italic bold___ bold*
"

## Optional set http proxy.
# export http_proxy="http://127.0.0.1:3128"
# export https_proxy="http://127.0.0.1:3128"
# Use the curl command to send the message
curl -s -X POST https://api.telegram.org/bot$API_TOKEN/sendMessage -d chat_id=$CHAT_ID -d parse_mode="MarkdownV2" -d text="$MESSAGE_MD"
```
5. If you failed to send a message due to some error, try to do it after a couple of seconds, otherwise write in the log that it failed and attach http-response.

**Comment by jansppenrade2** [comment]
Hey @Keonik1,

You're keeping me busy! 😄
Thanks a lot for all the helpful information!

I like the idea, but I'll need some time to dive into the Telegram topic and test a few things.

**Comment by jansppenrade2** [comment]
Hi @Keonik1,

I've implemented the ability to send notifications via Telegram. However, I'm facing some challenges with splitting the message in case it exceeds the maximum length of 4096 characters. Currently, the script only checks the length of the message to be sent, and if it exceeds 4096 characters, an error will be logged, but the message will be discarded.

I'm not sure if I'll be able to implement message splitting, but you're welcome to test the script with Telegram notifications already.

Here's the link: [<link>](https://github.com/jansppenrade2/Docker-Container-Updater/blob/9337451192070bed6e13ef463aa3ca60fc5b3546/container_update.sh)

Please tell me what you think.

**Comment by Keonik1** [comment]
Hello @jansppenrade2 

Thanks!

I have tested the ability to send messages to telegram. It seems to work correctly for me.

About message splitting, I'll look at how to implement it here later, because I've done something like that in the past, but probably next week. 

If there are any suggestions for improvements, I'll post them in this issue or do it myself if it's easy to integrate.

**Comment by jansppenrade2** [comment]
This feature has been added in version 2024.05.26-1.
