### ISSUE TITLE
Failed to request available image tags

### ISSUE THREAD

**Issue by benjaminsabatini** [jansppenrade2/Docker-Container-Updater#25]
Hi, I get the following error every time I run the script or use the docker image.

`ERROR       => Failed to request available image tags: wget https://registry.hub.docker.com/v2/repositories/lscr.io/linuxserver/xyz/tags`

**Comment by jansppenrade2** [comment]
Hi @benjaminsabatini,

Could you please provide me with a full log in debug mode? *(Ensure sensitive data is removed)*. 

To do this, execute the following command directly on your Docker host:
```
docker exec Docker-Container-Updater dcu --run --debug --filter name="<container_name>"
```
Alternatively, you can execute:
```
dcu --run --debug --filter name="<container_name>"
```
within the container of Docker-Container-Updater.

Further Questions:
1. Could you share more about your container and network configuration? Is there anything blocking your Docker host or the Docker container from accessing https://registry.hub.docker.com/?
2. Is the Docker image you're trying to update publicly available, or is it a private repository?
3. Does this issue affect all your Docker containers or just specific ones?
4. Have you tried running the following command (e.g.) directly on your host or within the Docker-Container-Updater container?:
```
wget https://registry.hub.docker.com/v2/repositories/lscr.io/linuxserver/<your_image>/tags
```

Best regards,
Jan

**Comment by benjaminsabatini** [comment]
> wget https://registry.hub.docker.com/v2/repositories/lscr.io/linuxserver/<your_image>/tags

I think I found the issue.

My YAML file had: lscr.io/linuxserver/qbittorrent:latest. Changing it to: linuxserver/qbittorrent:latest allowed it to work without error.
